### ISSUE TITLE
Add wind speed

### ISSUE THREAD

**Issue by adammwilson** [BioSCape-io/terrestrial_sampling#1]
Get wind speed from [here](https://developers.google.com/earth-engine/datasets/catalog/NASA_FLDAS_NOAH01_C_GL_M_V001#bands).

Band: `Wind_f_tavg`

**Comment by bmaitner** [comment]
First draft available here: https://bioscape-io.github.io/terrestrial_sampling/flight_planning_wind 

Note that I broke this into a separate page to keep the file size down.
